### ISSUE TITLE
Extra space before initial location (city) parenthesis, and after semi-colon, and colon.

### ISSUE THREAD

**Issue by Nhapsie** [dcpurton/biblatex-sbl#32] opened 2016-04-04 07:30 UTC
I'm noticing one extra space in these two places, don't know if it's just my machine, or a coding typo. I might have to use the microtype package.

**Comment by dcpurton** [comment] 2016-04-04 07:35
Can you provide an example? Does the problem appear in the current biblatex-sbl-test.pdf?

**Comment by Nhapsie** [comment] 2016-04-04 07:43
yes, on biblatex-sbl-test and any other tex compilation. Check Biblatex Output against Reference Implementation for Talbert:1992, p. 3. But I think biblatex-sbl-test wil not show it accurately because it's text justified. On my end, when I use ragged right this problem is visible.

**Comment by Nhapsie** [comment] 2016-04-04 07:48
Take a look
<img width="955" alt="screen shot 2016-04-04 at 2 46 27 am" src="https://cloud.githubusercontent.com/assets/5918656/14241154/a609a83e-fa0f-11e5-8668-a98ffb5cdc23.png">

**Comment by Nhapsie** [comment] 2016-04-04 07:53
Compare space between "CBQ 29.3 (1967)" and "AnBib 21A  (Rome:" and several other instances.

**Comment by dcpurton** [comment] 2016-04-04 07:56
Ah yep, I see.

**Comment by dcpurton** [comment] 2016-04-04 08:01
Should be fixed. Try now.

**Comment by Nhapsie** [comment] 2016-04-04 08:01
Note also also this

**Comment by Nhapsie** [comment] 2016-04-04 08:07
Extra space is kind of hard to put your finder at, but we're getting there.

**Comment by Nhapsie** [comment] 2016-04-04 08:18
extra space before parenthesis solved, now we need to adjust space after semi-colon

**Comment by dcpurton** [comment] 2016-04-04 09:08
Can you provide the code that exhibits this?

**Comment by dcpurton** [comment] 2016-04-04 09:22
oh - wait - maybe we posted at about the same time. Are all these fixed in the latest dev branch? Or is the last one still not working for you?

**Comment by Nhapsie** [comment] 2016-04-04 14:36
you closed before I posted the second request, which has to do with semi-colon and colon extra space. But the first request is fixed

**Comment by dcpurton** [comment] 2016-04-04 14:37
I can reproduce it actually.

**Comment by Nhapsie** [comment] 2016-04-04 14:45
I'm about to list the codes, if you want...

**Comment by dcpurton** [comment] 2016-04-04 15:01
Don't worry. Though I can't track down where the error is yet

**Comment by dcpurton** [comment] 2016-04-12 01:26
Can you check if things are fixed now?

**Comment by Nhapsie** [comment] 2016-04-12 02:07
- space after series fixed (CBQ, AnaBib example)
- space after colon in titles need fixing
- some cases of space after year/parenthesis need adjustment

**Comment by Nhapsie** [comment] 2016-04-12 02:30
If examples in biblatex-sbl can be flushed to the left instead of justified the spacing can be easier to spot. The `\frenchspacing` improved a good deal. What I see now is 1.5 space. At this point I don't think it's worth messing with it, not a big deal.

**Comment by dcpurton** [comment] 2016-04-12 06:04
I don't think these remaining things you are seeing are with spacing in `biblatex-sbl`. Your colon spacing is certainly to do with `\frenchspacing` and I think some of your other spacing concerns are related to how the font behaves in italic shape.

This MWE shows your examples above as produced by the style and as typeset directly. I cannot see any difference between the output. (BTW, is there a typo in the title of Gorman - should be ";" not "," after *Lev 8*? And should you be using a colon, not period to separate the title from the subtitle in *Treat and Covenant* and *Mighty Acts of God*? (See §6.1.3.1 of SBLHS)

```
\documentclass[12pt]{article}

\usepackage{times}
\usepackage[ragged]{footmisc}
\usepackage{filecontents}
\begin{filecontents}{\jobname.bib}
@review{anderson:1995,
  author = {Anderson, Gary A.},
  revdauthor = {Douglas, Mary},
  revdtitle = {In the Wilderness: The Doctrine of Defilement in the Book of Numbers},
  journaltitle = {Critical Review of Books in Religion},
  shortjournal = {CRBR},
  volume = {8},
  number = {1},
  date = {1995},
  pages = {119-121}
}
@thesis{gorman:1985,
  author = {Gorman, Frank H.},
  title = {Priestly Ritual and Creation Theology: The Conceptual Categories of Space, Time, and Status in Lev 8; 14; 16; Num 19; 28--39},
  type = {phdthesis},
  institution = {Emory University},
  date = {1985}
}
@book{mccarthy:1978,
  author = {McCarthy, Dennis J.},
  title = {Treaty and Covenant: A Study in Form in the Ancient Oriental Documents and in the Old Testament},
  edition = {2},
  series = {Analecta Biblica},
  shortseries = {AnBib},
  number = {21A},
  location = {Rome},
  publisher = {Pontifical Biblical Institute},
  date = {1978}
}
@article{mccarthy:1967,
  author = {McCarthy, Dennis J.},
  title = {Creation Motifs in Ancient Hebrew Poetry},
  journaltitle = {Catholic Biblical Quarterly},
  shortjournal = {CBQ},
  volume = {29},
  number = {3},
  date = {1967},
  pages = {393-406}
}
@incollection{mendenhall:1976,
  author = {Mendenhall, Geroge E.},
  title = {Social Organization in Early Israel},
  booktitle = {Mighty Acts of God: Essays on the Bible and Archaeology in Memory of G. Ernest Wright},
  editor = {Cross, Frank M. and Lemke, W. E. and Miller, Patrick D.},
  location = {Garden City, N.Y.},
  publisher = {Doubleday},
  date = {1976},
  pages = {132-151}
}
@article{mendenhall:1958,
  author = {Mendenhall, Geroge E.},
  title = {The Census Lists of Numbers 1 and 26},
  journaltitle = {Journal of Biblical Literature},
  shortjournal = {JBL},
  volume = {77},
  date = {1958},
  pages = {52-66}
}
\end{filecontents}

\usepackage[style=sbl,citepages=permit,backend=biber,ibidtracker=constrict,idemtracker=constrict,pagetracker,ibidpage,sblfootnotes=false]{biblatex}
\addbibresource{\jobname.bib}

\frenchspacing
\raggedright

\begin{document}

\autocite[120-121]{anderson:1995}

\footnote{Gary A. Anderson, review of \emph{In the Wilderness: The Doctrine of
Defilement in the Book of Numbers,} by Mary Douglas, \emph{CRBR} 8.1 (1995):
119--21 (120--21).}

\autocites[77-90]{gorman:1985}[12-15]{anderson:1995}

\footnote{Frank H. Gorman, ``Priestly Ritual and Creation Theology: The Conceptual
Categories of Space, Time, and Status in Lev 8; 14; 16; Num 19; 28--39'' (PhD
diss., Emory University, 1985), 77--90; Anderson, review of \emph{In the
Wilderness} (by Douglas), 12--15.}

\autocites{mccarthy:1978}[78]{mccarthy:1967}{mendenhall:1976}[84]{mendenhall:1958}

\footnote{Dennis J. McCarthy, \emph{Treaty and Covenant: A Study in Form in
the Ancient Oriental Documents and in the Old Testament,} 2nd ed., AnBib 21A
(Rome: Pontifical Biblical Institute, 1978); idem, ``Creation Motifs in
Ancient Hebrew Poetry,'' CBQ 29.3 (1967): 393--406 (78); Geroge E. Mendenhall,
``Social Organization in Early Israel,'' in \emph{Mighty Acts of God: Essays
on the Bible and Archaeology in Memory of G. Ernest Wright,} ed. Frank M.
Cross, W. E. Lemke, and Patrick D. Miller (Garden City, N.Y.: Doubleday,
1976), 132--51; idem, ``The Census Lists of Numbers 1 and 26,'' JBL 77 (1958):
52–66 (84).}

\end{document}
```

![test](https://cloud.githubusercontent.com/assets/6268044/14451145/ccba7a84-00c3-11e6-86b3-5ce87db6c855.png)

**Comment by Nhapsie** [comment] 2016-04-12 07:45
Thanks for pointing out the typo on Gorman, and Mendenhall as well. Here is the thing I just realized when I compiled your MWE on my end: we're using different types of Times font. Yours is the standard, and mine is not and I don't know how to fix it. My Times has italics more pronounced, less density too; check the "Q" on "CBQ" and you will see right away the difference between the fonts. This is the culprit in regard to spacing. I think, I really don't like my font. Here's what I have on the cls: 
`\setromanfont[Mapping=tex-text,
              BoldFont=Times_New_Roman_Bold.ttf,
              ItalicFont=Times_New_Roman_Italic.ttf,
              BoldItalicFont=Times_New_Roman_Bold_Italic.ttf]{Times_New_Roman.ttf}
\setsansfont[Mapping=tex-text,
             BoldFont=Arial_Bold.ttf,
             ItalicFont=Arial_Italic.ttf,
             BoldItalicFont=Arial_Bold_Italic.ttf]{Arial.ttf}`
I have no clue why Arial is important, can I get rid of it without consequences? A few notes: (1) check why your MWE is not italicizing CBQ and JBL (2) omit one instance of "with a" on page 6 of biblatex-sbl.pdf.

**Comment by Nhapsie** [comment] 2016-04-12 08:38
Thanks for pointing out the typo on Gorman, and Mendenhall as well. When I compiled your MWE I realized the italics are great compared to mine which are too pronounced, slanted. You had mentioned it had to do with italics, but I didn't realize that my Times is actually different from yours. I must be doing something wrong here, because I used the same cls to compile yours and mine! 

Suggestions: (1) check why your MWE is not italicizing CBQ and JBL (2) omit one instance of "with a" on page 6 of biblatex-sbl.pdf.

**Comment by dcpurton** [comment] 2016-04-12 09:35
You should be able to get rid of all your times and arial font lines and replace them with `\usepackage{times}`. If you do this, you can also get rid of the fake small caps, since I think the times package includes actual small caps fonts.

CBQ and JBL are not italicised in the typeset version because I forgot to enclose them in `\emph{}`. They are fine in the output produced by `biblatex-sbl`

**Comment by dcpurton** [comment] 2016-04-12 09:39
I fixed the typo in `biblatex-sbl`. Thanks! Looks like I can close this one. Open a new issue if you find any more places where a double space is being inserted.

**Closed** 2016-04-12 09:40 UTC

**Comment by Nhapsie** [comment] 2016-04-12 10:31
`\usepackage{times}` did not work, but `\setmainfont{Times}` under `\RequirePackage{fontspec}` did the trick. The only change I notice is bigger footnote numbers in the text (aesthetics only).

**Comment by dcpurton** [comment] 2016-04-12 10:37
The `times` package might not be compatible with `fontspec` actually. It's an old package using PostScript fonts from memory.
